version: "3.8"

services:
    application:
        container_name: ${CONTAINER_NAME?err}
        build:
            context: .
            dockerfile: dockerfile
            args:
                GIT_REPO_URL: ${GIT_REPO_URL?err}
        ports:
            - "${EXTERNAL_PORT?err}:${INTERNAL_PORT?err}"
        volumes:
            - env:/application/env
        # deploy:
        #     resources:
        #         limits:
        #             cpus: "0.1"
        #             memory: 50M
        #         reservations:
        #             cpus: "0.1"
        #             memory: 50M

volumes:
    env:
